name: Deploy static content to Pages

on:
  push:
    branches: "main"

  # Allow manual runs
  workflow_dispatch:
    branches: "main"

# Permissions for Github Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only the most recent trigger to run
concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2
        with:
          enablement: true

      - name: Cache Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Upload build
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v1

      - name: Cleanup build
        uses: geekyeggo/delete-artifact@v2
        with:
          name: github-pages

      # Uses puppeteer to build pdf headless
      - name: Generate PDF
        uses: dashdotme/html-to-pdf-action@v2
        with:
          htmlFile: ./dist/index.html
          outputFile: ./pdf/DV_CV_public.pdf

      # Note: workflow pushes don't trigger workflows
      - name: Push PDF to git
        env: 
          ci_email: 35617767+dashdotme@users.noreply.github.com
          ci_author: dashdotme_pipelines
          ci_cmt_msg: "chore: updated pdf"
        run: |
          git config --global user.name "${{ env.ci_author }}"
          git config --global user.email "${{ env.ci_email }}"
          git commit -a -m "${{ env.ci_cmt_msg }}"
          git push

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: DV_CV_public.pdf
          path: ./pdf/
